# This is where functions go that I don't want to re-define every time I'll have to use them.
# Textwrap function generated by Claude Sonnet 4.6, lightly edited by Luke Kuruvilla.

import textwrap
import sqlite3


def get_db():
    db = sqlite3.connect("db/game.db")
    db.row_factory = sqlite3.Row
    return db


def wrap_text(text: str, width: int = 80, indent: int = 0) -> str:
    """
    Wrap a block of text to fit a terminal of a given column width.

    Preserves paragraph breaks (blank lines), handles leading whitespace
    per paragraph, and optionally indents every line by `indent` spaces.

    Args:
        text:   The raw string to wrap (may contain newlines and blank lines).
        width:  Maximum line width in columns (default 80).
        indent: Number of spaces to prepend to every output line (default 0).

    Returns:
        A single string with line breaks inserted for clean terminal display.

    Example of usage:

    >>> raw = open("help.txt").read()
    >>> print(wrap_text(raw, width=72, indent=2))

    """
    prefix = " " * indent
    effective_width = width - indent

    paragraphs = text.split("\n\n")
    wrapped_paragraphs = []

    for para in paragraphs:
        # Collapse internal newlines / extra spaces within a paragraph
        para = " ".join(para.split())
        if not para:
            wrapped_paragraphs.append("")
            continue
        wrapped = textwrap.fill(
            para,
            width=effective_width,
            initial_indent=prefix,
            subsequent_indent=prefix,
        )
        wrapped_paragraphs.append(wrapped)

    return "\n\n".join(wrapped_paragraphs)

def parse_target_and_index(args: list[str]) -> tuple[str, int]:
    """
    Given args like ['cap', '2'] or ['goblin', '2'] or ['iron', 'cap'],
    returns (name, index) where index defaults to 1.
    
    Examples:
        ['cap', '2']       → ('cap', 2)
        ['iron', 'cap']    → ('iron cap', 1)
        ['goblin']         → ('goblin', 1)
        ['goblin', '2']    → ('goblin', 2)
    """
    if args and args[-1].isdigit():
        return " ".join(args[:-1]), int(args[-1])
    return " ".join(args), 1