# This is where functions go that I don't want to re-define every time I'll have to use them.
# Textwrap function generated by Claude Sonnet 4.6, lightly edited by Luke Kuruvilla.

import textwrap
import sqlite3

MAX_LEVEL=20

XP_TABLE = {
    1: 300,
    2: 500,
    3: 800,
    4: 1200,
    5: 1700,
    6: 2300,
    7: 3000,
    8: 3800,
    9: 4700,
    10: 5800,
    11: 7000,
    12: 8500,
    13: 10000,
    14: 12000,
    15: 14500,
    16: 17500,
    17: 21000,
    18: 25000,
    19: 35000
}

AGGRO_TIMER = 1200


def get_db():
    db = sqlite3.connect("db/game.db")
    db.row_factory = sqlite3.Row
    return db


def wrap_text(text: str, width: int = 80, indent: int = 0) -> str:
    """
    Wrap a block of text to fit a terminal of a given column width.

    Preserves paragraph breaks (blank lines), handles leading whitespace
    per paragraph, and optionally indents every line by `indent` spaces.

    Args:
        text:   The raw string to wrap (may contain newlines and blank lines).
        width:  Maximum line width in columns (default 80).
        indent: Number of spaces to prepend to every output line (default 0).

    Returns:
        A single string with line breaks inserted for clean terminal display.

    Example of usage:

    >>> raw = open("help.txt").read()
    >>> print(wrap_text(raw, width=72, indent=2))

    """
    prefix = " " * indent
    effective_width = width - indent

    paragraphs = text.split("\n\n")
    wrapped_paragraphs = []

    for para in paragraphs:
        # Collapse internal newlines / extra spaces within a paragraph
        para = " ".join(para.split())
        if not para:
            wrapped_paragraphs.append("")
            continue
        wrapped = textwrap.fill(
            para,
            width=effective_width,
            initial_indent=prefix,
            subsequent_indent=prefix,
        )
        wrapped_paragraphs.append(wrapped)

    return "\n\n".join(wrapped_paragraphs)


def parse_target_and_index(args: list[str]) -> tuple[str, int]:
    """
    Given args like ['cap', '2'] or ['goblin', '2'] or ['iron', 'cap'],
    returns (name, index) where index defaults to 1.

    Examples:
        ['cap', '2']       → ('cap', 2)
        ['iron', 'cap']    → ('iron cap', 1)
        ['goblin']         → ('goblin', 1)
        ['goblin', '2']    → ('goblin', 2)
    """
    if args and args[-1].isdigit():
        return " ".join(args[:-1]), int(args[-1])
    return " ".join(args), 1

def get_npc_name(target, db):
    row = db.execute(
        """SELECT npc_templates.name FROM npc_instances
           JOIN npc_templates ON npc_instances.template_id = npc_templates.id
           WHERE npc_instances.id = ?""",
        (target["id"],)
    ).fetchone()
    return row["name"] if row else "your target"


def get_health_condition(current: int, maximum: int) -> str:
    """Returns a readable health condition string for an NPC."""
    if maximum <= 0:
        return "is in an unknown state"
    
    percent = current / maximum

    if percent >= 1.0:
        return "is in perfect condition"
    elif percent >= 0.75:
        return "has a few scratches"
    elif percent >= 0.50:
        return "is bleeding lightly"
    elif percent >= 0.25:
        return "looks badly wounded"
    else:
        return "is near death"