# Generated by Claude, edited by Luke Kuruvilla.

import random

STATS = ["STR", "DEX", "CON", "INT", "WIS", "CHA"]


def roll_stat():
    """Roll 3d6."""
    return sum(random.randint(1, 6) for _ in range(3))


def roll_all_stats():
    """Roll a full set of 6 stats."""
    return [roll_stat() for _ in range(6)]


def assign_stats():
    """Let the player roll stats and assign them."""

    # Rolling phase
    rolls = sorted(roll_all_stats(), reverse=True)
    print()
    print("Your six stats are STR, DEX, CON, INT, WIS, and CHA.")
    print("STR: Your strength, which affects your carrying capacity and weapon attacks.")
    print("DEX: Your dexterity, which affects some weapon attacks and your defense.")
    print("CON: Your constitution, which affects your endurance and health.")
    print("INT: Your intelligence, which affects your ability for intellectual work.")
    print("WIS: Your wisdom, which affects your perception, intuition, and insight.")
    print("CHA: Your charisma, which affects your ability to persuade or trick.")
    print("Each is rolled with 3d6. You may reroll your results once.")
    print("Afterwards, you'll assign each value to a stat of your choice.\n")
    print("You rolled the following values (highest to lowest):")
    for i, val in enumerate(rolls, 1):
        print(f"  {i}. {val}")
    print()

    reroll = input("Would you like to use your reroll? (yes/no)\n> ").strip().lower()
    if reroll in ("yes", "y"):
        print("\nVery well. Rolling again...\n")
        rolls = sorted(roll_all_stats(), reverse=True)
        print("You rolled the following values (highest to lowest):")
        for i, val in enumerate(rolls, 1):
            print(f"  {i}. {val}")
        print()

    # Assignment phase
    assigned = {}
    remaining_stats = STATS[:]
    remaining_rolls = rolls[:]

    print("Now assign your rolls to your stats.")
    print("You will assign them highest to lowest.\n")

    for roll in remaining_rolls:
        print(f"Assign {roll} to which stat?")
        for i, stat in enumerate(remaining_stats, 1):
            print(f"  {i}. {stat}")
        print()

        while True:
            choice = input("> ").strip()
            if choice.isdigit() and 1 <= int(choice) <= len(remaining_stats):
                chosen_stat = remaining_stats.pop(int(choice) - 1)
                assigned[chosen_stat] = roll
                print(f"\n{chosen_stat} set to {roll}.\n")
                break
            print("Invalid choice. Please enter a number from the list.")

    # Summary
    print("Your final stats:")
    for stat, val in assigned.items():
        print(f"  {stat}: {val}")
    print()

    return assigned
