# Generated by Claude.

import sqlite3
from game.models import Room

def get_test_db():
    """Create an in-memory database with just enough schema to test Room."""
    db = sqlite3.connect(":memory:")
    db.row_factory = sqlite3.Row
    db.executescript("""
        CREATE TABLE rooms (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            lighting INTEGER NOT NULL DEFAULT 1,
            smell TEXT NOT NULL DEFAULT '',
            sound TEXT NOT NULL DEFAULT '',
            area TEXT NOT NULL DEFAULT 'city',
            movement_cost INTEGER DEFAULT 3
        );
        
        CREATE TABLE exits (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            room_id INTEGER NOT NULL,
            direction TEXT NOT NULL,
            destination_room_id INTEGER NOT NULL
        );
        
        INSERT INTO rooms (name, description, area) 
            VALUES ('Town Square', 'A bustling square.', 'city');
        INSERT INTO rooms (name, description, area) 
            VALUES ('Dark Alley', 'A narrow alley.', 'city');
        
        INSERT INTO exits (room_id, direction, destination_room_id)
            VALUES (1, 'north', 2);
        INSERT INTO exits (room_id, direction, destination_room_id)
            VALUES (2, 'south', 1);
    """)
    return db

def test_get_by_id():
    db = get_test_db()
    room = Room.get_by_id(db, 1)
    assert room is not None, "Room should exist"
    assert room.name == "Town Square", f"Expected 'Town Square', got '{room.name}'"
    assert room.id == 1, f"Expected id 1, got {room.id}"
    print("PASS: test_get_by_id")

def test_get_by_id_missing():
    db = get_test_db()
    room = Room.get_by_id(db, 999)
    assert room is None, "Should return None for nonexistent room"
    print("PASS: test_get_by_id_missing")

def test_get_exits():
    db = get_test_db()
    room = Room.get_by_id(db, 1)
    exits = room.get_exits(db)
    assert len(exits) == 1, f"Expected 1 exit, got {len(exits)}"
    assert exits[0]["direction"] == "north", f"Expected 'north', got '{exits[0]['direction']}'"
    print("PASS: test_get_exits")

def test_get_exits_empty():
    db = get_test_db()
    db.execute("INSERT INTO rooms (name, description) VALUES ('Void', 'Nothing here.')")
    db.commit()
    room = Room.get_by_id(db, 3)
    exits = room.get_exits(db)
    assert exits == [], "Room with no exits should return empty list"
    print("PASS: test_get_exits_empty")

def test_describe():
    db = get_test_db()
    room = Room.get_by_id(db, 1)
    description = room.describe(db)
    assert "Town Square" in description, "Description should contain room name"
    assert "bustling square" in description, "Description should contain room description"
    assert "north" in description, "Description should list exits"
    print("PASS: test_describe")

if __name__ == "__main__":
    test_get_by_id()
    test_get_by_id_missing()
    test_get_exits()
    test_get_exits_empty()
    test_describe()
    print("\nAll tests passed.")